site_name: milynnus Consulting Blog
site_description: A blog site built with Materials for Mkdocs
site_url: https://milynnus-blog.com
theme:
  name: material
  features:
    - navigation.footer
  custom_dir: overrides
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        name: Switch to system preference

plugins:
  - search
  - blog:
      blog_dir: .
      archive_date_format: MM yyyy
      post_url_format: "{categories}/{slug}"
      post_url_max_categories: 2
      categories_allowed:
        - Life
        - Articles
        - Documentation
  - tags:

  - rss:
      match_path: "/posts/.*"
      pretty_print: true
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

  - git-committers:
      repository: xu2xulim/milynnus-blog
      branch: main

extra:
  social:
    - icon: simple/youtube
      link: https://youtube.com/@james-willett
    - icon: simple/linkedin
      link: https://linkedin.com/in/willettjames

copyright: Copyright &copy; 2024 James Willett


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


  

